/*
 * Copyright 2019 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.gov.hmrc.cdsimportsddsfrontend.services

object DmsErrorCodes {

  val codes = Map(
  "ABC"       -> "Conditions of sale or purchase",
  "ACA"       -> "Documentary requirements",
  "ACB"       -> "Additional Information",
  "ACD"       -> "Amendment Text",
  "AES"       -> "Textual Explanation",
  "AFB"       -> "Customs Position Motivation,",
  "BLF"       -> "Control Explanation",
  "CEX"       -> "Customs clearance instructions export",
  "CUS"       -> "Special Mentions",
  "TRR"       -> "Tariff Quota Order Number",
  "ZZZ"       -> "Mutually Defined",
  "COR"       -> "Request for correction",
  "GPR"       -> "Goods presentation message",
  "INV"       -> "Request for invalidation",
  "CV"        -> "Customs article number defined by Customs authorities to an article or a group of articles for Customs purposes.",
  "GN"        -> "National product group code administered by a national agency.",
  "SSO"       -> "UN list to classify dangerous goods",
  "TRA"       -> "TARIC additional code",
  "TRC"       -> "TARIC code",
  "TSP"       -> "Combined nomenclature code",
  "1"         -> "Document control",
  "2"         -> "Physical control",
  "3"         -> "Undetermined",
  "1"         -> "Amend commodity code",
  "2"         -> "Amend value",
  "3"         -> "Amend tax line(s)",
  "4"         -> "Amend preference",
  "5"         -> "Amend quota",
  "6"         -> "Amend license",
  "7"         -> "Amend currency",
  "8"         -> "Amend CPC",
  "9"         -> "Amend weight or quantity",
  "10"        -> "Amend consignee/consignor",
  "12"        -> "Nil amendment - please state reason",
  "13"        -> "Other - please state reason",
  "16"        -> "Goods presentation notice",
  "1"         -> "Non-preferential origin",
  "2"         -> "Preferential origin",
  "1"         -> "Declaration is no longer required",
  "2"         -> "Duplicate declaration (MRN of new declaration provided)",
  "3"         -> "Other reason for cancellation",
  "A1"        -> "All Declarations which have not resulted in A2 or B1",
  "A2"        -> "There are no Control Tasks for the Declaration",
  "B1"        -> "There is a “Major Discrepancy” Control Result for the Declaration",
  "ACS"       -> "Account Sales",
  "CEP"       -> "CAP Entry Price",
  "CRQ"       -> "Critical Quota",
  "CSD"       -> "CAP Safeguard Duties",
  "ENU"       -> "End-Use (Authorisation by Declaration)",
  "IPR"       -> "Inward Processing (ABD)",
  "MDC"       -> "Missing Document CSDR",
  "MDL"       -> "Missing document - License Quota",
  "MDP"       -> "Missing document - Preference Document",
  "MOD"       -> "Manual Override deposit",
  "OPR"       -> "Outward Processing (ABD)",
  "PDD"       -> "Provisional Dumping Duty",
  "RED"       -> "Revenue Dispute",
  "T24"       -> "Temporary Admission (2 years Expiration)",
  "TA2"       -> "Temporary Admission TA (2 months Expiration)",
  "TA3"       -> "Temporary Admission TA (3 months Expiration)",
  "TA6"       -> "TA (6 months Expiration)",
  "1"         -> "General additional information belonging to declaration validation result",
  "2"         -> "Additional unit type belonging to declaration validation result",
  "3"         -> "Supplementary unit type belonging to declaration validation result",
  "4"         -> "Commodity code belonging to declaration validation result",
  "5"         -> "Document type belonging to declaration validation result",
  "6"         -> "Action code belonging to declaration validation result",
  "7"         -> "Condition code belonging to declaration validation result",
  "8"         -> "Measure ID belonging to declaration validation result",
  "9"         -> "Document occurence type belonging to declaration validation result",
  "CDS10001"  -> "Obligation Error: Mandatory Data Element has not been provided",
  "CDS10002"  -> "Obligation Error: Data Element is not allowed",
  "CDS10003"  -> "Obligation Error: Number of Occurrences exceeds what is allowed for the Data Element",
  "CDS10004"  -> "Commodity code Error: Mandatory data element not provided and/or format error and/or number of occurrences exceeds what is allowed for the data element",
  "CDS10010"  -> "Format Error: Data element has invalid format",
  "CDS10020"  -> "Data Error: Data Element contains invalid value",
  "CDS10021"  -> "Data Error: Value must be positive",
  "CDS10044"  -> "Document is not allowed",
  "CDS10045"  -> "Calculated item Customs value is negative. Check Declaration valuation data",
  "CDS11003"  -> "Relation Error: The value declared in Total Number of Items (D.E. 1/9) does not corespond with the number of Goods Items on the Declaration",
  "CDS11004"  -> "Relation Error: The combination of the Requested Procedure, Previous Procedure and Additional Procedure is invalid",
  "CDS11005"  -> "Relation Error: The Requested Procedure (D.E. 1/10) for each Goods Item must derive the same Declaration Category (e.g. H1)",
  "CDS11006"  -> "Relation Error: Net Mass must be lower than Gross Mass",
  "CDS11007"  -> "Relation Error: The submitter of the Additional Message differs from the original Declaration",
  "CDS11012"  -> "Element is not allowed to be amended on this Declaration Type",
  "CDS12003"  -> "Uniqueness Error: Reuse of LRN (D.E. 2/5) is not allowed within 48 hours",
  "CDS12005"  -> "Authorisation Error: Party ID unknown or invalid.",
  "CDS12006"  -> "Authorisation Warning: Invalid import/export license number",
  "CDS12007"  -> "Authorisation Error: Authorisation has expired; or Authorisation reference number does not belong to the party on the declaration; or Authorisation reference number provided is not recognised",
  "CDS12008"  -> "Authorisation Error: Requested amount or quantity is not available for license reservation",
  "CDS12013"  -> "Authorisation Error: provided VAT number is not a valid destination for VAT transfer",
  "CDS12014"  -> "Sequence Error: A Goods Arrival Notification must follow a pre-lodged Declaration",
  "CDS12015"  -> "Sequence Error: AdditionalMessage.declarationReference does not refer to an existing declaration or the existing declaration is not in a permissable state to process the request",
  "CDS12016"  -> "Date Error: The acceptance date must not be in the future and must not be more than 180 days in the past",
  "CDS12022"  -> "Relation Error: The Goods Item Number (D.E. 1/6) is larger than the total number of Goods Items on the Declaration",
  "CDS12024"  -> "Uniqueness Error: The value declared should be unique",
  "CDS12026"  -> "Uniqueness Error: The same Data Element cannot be amended more than once in the same request",
  "CDS12031"  -> "Sequence Error: Goods Arrival Notification must be submitted within 30 days",
  "CDS12032"  -> "Sequence Error: A request for correction can no longer be submitted because a CustomsPosition has been determined already for the related declaration.",
  "CDS12034"  -> "Relation Error: Submission channel of the amendment must be the same as the original Declaration",
  "CDS12036"  -> "Sequence Error: A new request cannot be submitted until a response is received to your previous request",
  "CDS12042"  -> "Relation Error: elements must be identical within the GoodsItem",
  "CDS12046"  -> "Process Error: Goods Arrival Notification was not received within 30 days of the pre-lodged Declaration",
  "CDS12050"  -> "A valid Requested Procedure (D.E. 1/10) has not been provided. No further validation has been carried out",
  "CDS12052"  -> "A valid Declaration Type (D.E. 1/2) has not been provided. No further validation has been carried out",
  "CDS12054"  -> "Relation Error: the following parties must be identical",
  "CDS12056"  -> "Relation Error: the combination of elements is not allowed",
  "CDS12057"  -> "Relation Error: The invoice currency must be the same for every Goods Item on the Declaration",
  "CDS12058"  -> "Relation Error: When the packaging quantity is zero, then there must be another goods item with the same marks and numbers having a quantity greater than zero",
  "CDS12070"  -> "Relation Error: The value supplied in Data Element 1 mandates the completion of Data Element 2",
  "CDS12071"  -> "Relation Error: Data Element must be supplied at either header or item level and cannot be declared at both levels",
  "CDS12072"  -> "Relation Error: Either Data Element 1 or Data Element 2 must be supplied, but not both",
  "CDS12073"  -> "Relation Error: Data Element must be supplied at header or item level",
  "CDS12074"  -> "Relation Error: Because Data Element 1 is not supplied, Data Element 2 is mandatory",
  "CDS12075"  -> "Relation Error: Data Element 2 must not be supplied with this value in Data Element 1",
  "CDS12077"  -> "Relation Error: A valid value must be supplied in Data Element 2 as Data Element 1 is present",
  "CDS12078"  -> "Relation Error: As no Deferment Account Number is provided in D.E. 2/6, an immediate Method of Payment must be offered in D.E. 4/8",
  "CDS12079"  -> "Relation Error: Data Element 2 must not be supplied with Data Element 1",
  "CDS12080"  -> "Relation Error: Combination of Addition / Deduction codes (D.E. 4/9) is not allowed",
  "CDS12081"  -> "Relation Error: Importer (D.E. 3/16) & Exporter (D.E. 3/2) must not be the same party",
  "CDS12082"  -> "Relation Error: The currency declared in D.E. 4/11 must be the same as the currency declared in D.E. 4/14",
  "CDS12083"  -> "Relation Error: For Country of Preferential Origin D.E. 5/16 where mandated, only provide one country or country group, not both",
  "CDS12084"  -> "Relation Error: Either Consignee Name (D.E. 3/9) or Consignee Identification Number (D.E. 3/10) must be supplied, but not both",
  "CDS12085"  -> "Relation Error: Delivery Destination (DE 5/8 or 5/9) must be supplied at either header or item level and cannot be declared at both",
  "CDS12086"  -> "Relation Error: Either Carrier Name (D.E. 3/31) or Carrier Identification Number (D.E. 3/32) must be supplied, but not both",
  "CDS12087"  -> "Relation Error: VAT Declaring Party Identification (D.E. 3/40), where mandated, must be supplied at either header or item",
  "CDS12088"  -> "Relation Error: Either Agent Name (D.E. 3/19) or Agent Identification Number (D.E. 3/20) must be supplied",
  "CDS12089"  -> "Relation Error: Consignee Party Name (D.E.3/9) must be supplied at either header or item level",
  "CDS12090"  -> "Relation Error: Carrier Name (D.E. 3/31) or Carrier Identification Number (D.E. 3/32) must be supplied for the 17X Additional Procedure Code at either header or item level",
  "CDS12091"  -> "Relation Error: Consignee (D.E. 3/10) & Exporter (D.E. 3/1) must not be the same Party",
  "CDS12092"  -> "Relation Error: Seller (D.E. 3/25) & Exporter (D.E. 3/1) must not be the same Party",
  "CDS12094"  -> "Relation Error: Additional Document C505 is required with Requested Procedure 71",
  "CDS12095"  -> "Relation Error: Additional Procedure Combination (D.E. 1/11) can only be used when Country of Dispatch/Export (D.E. 5/14) Exportation Country is a Third Country",
  "CDS12096"  -> "Relation Error: Provided Authorisation Type (D.E. 3/39) requires specific document in Additional Documents",
  "CDS12097"  -> "Relation Error: Combination Additional Procedure Code (D.E. 1/11) and Country of Destination in D.E. 5/8 is not allowed",
  "CDS12098"  -> "Relation Error: Combination of Means of Transport (D.E. 7/14) and Delivery Terms in D.E. 4/1 is not allowed",
  "CDS12099"  -> "Relation Error: Combination of elements that make up the Goods Location Code (D.E. 5/23) is invalid",
  "CDS12100"  -> "Relation Error: Combination of Delivery terms (D.E. 4/1) and Addition/Deduction code (D.E. 4/9) is not allowed",
  "CDS12101"  -> "Relation Error: Declared Tax Type (D.E. 4/3) is not allowed in combination with the Additional Procedure",
  "CDS12102"  -> "Relation Error: Deferred Payment Method in D.E. 4/8 is Required with the duty deferment account number provided in D.E. 2/6",
  "CDS12103"  -> "Relation Error: Valid delivery destination is required in D.E. 5/8 for a CO declaration",
  "CDS12104"  -> "Relation Error: Valid Import Procedure code (D.E. 1/10) is required",
  "CDS12105"  -> "Relation Error: Addition/Deduction code (D.E. 4/9) not allowed with the declared Additional Procedure Code (D.E.1/11)",
  "CDS12106"  -> "Relation Error: Appropriate Additional Information Code must be provided in D.E. 2/2 with Additional Procedure Code 1CL",
  "CDS12107"  -> "Relation Error: Conditions not met for the requested simplification. Please see CDS Trade Tariff Vol.3 Appendix 4",
  "CDS12108"  -> "Obligation Error: DUCR is mandatory on an Export Declaration",
  "CDS12109"  -> "Obligation Error: When providing fixed rate of exchange rate in D.E. 4/15, a currency code of GBP must be supplied",
  "CDS12110"  -> "Relation Error: A Quota Order number (D.E. 8/1) cannot be provided in combination with this Preference Code (D.E. 4/17)",
  "CDS12111"  -> "Relation Error: The provided tax amount (D.E. 4/6 or D.E. 4/7) must always be declared with currency code GBP",
  "CDS12112"  -> "Relation Error: Airfreight related additions/deduction code must be provided in DE 4/9 when an airport place of loading is provided in DE 5/21",
  "CDS12113"  -> "Relation Error: Authorisation holder CGU requires a guarantee type of 0 or 1 to be provided in D.E.8/2",
  "CDS12114"  -> "Relation Error: Value declared must be less than 100 as D.E. 4/9 Additions/Deductions code is a percentage",
  "CDS12115"  -> "Relation Error: Declared Procedure Code (D.E. 1/10 and / or 1/11) mandates the use of Additional Document (D.E. 2/3) 185C",
  "CDS12117"  -> "Relation Error: Importer (D.E. 3/16) & Buyer (D.E. 3/27) must not be the same party",
  "CDS12118"  -> "Relation Error: Consignor (D.E.3/1) information must be supplied for the 17X Additional Procedure Code at either header or item level and cannot be declared at both levels",
  "CDS12119"  -> "Relation Error: Declared Additional Document (D.E. 2/3) is not allowed with this Procedure Code (D.E. 1/10 or D.E. 1/11)",
  "CDS12120"  -> "Relation Error: The appropriate authorisation has not been declared for this Declaration Type (D.E. 1/2)",
  "CDS12121"  -> "Relation Error: This combination of Additional Information codes (D.E. 2/2) is not allowed",
  "CDS12122"  -> "Relation Error: Additional Procedure Code 1PS and 2PS must always be declared with C07 or 1LV additional procedure code in D.E.1/11",
  "CDS12123"  -> "Data Error: Value must be greater than 0",
  "CDS12124"  -> "License Error: License has expired; or License ID cannot be recognised; or License ID does not belong to the party on the declaration; or License declared has insufficient balance remaining; or License does not apply to the goods or country declared",
  "CDS12125"  -> "DAN Error: Account number is not recognised; or Account is suspended or revoked; or Parties declared on the declaration do not have authority to use account number provided",
  "CDS12126"  -> "Relation Error: When declaring the Authorisation code ‘MIB’ in D.E. 3/39, either ‘MIB01’ or ‘MIB02’ must be provided as an AI code in D.E. 2/2",
  "CDS12127"  -> "Relation Error: Conflicting autodeparture prompts. Either ‘MIB01’ or ‘MIB02’ can be declared in D.E. 2/2 but not both together on the same declaration",
  "CDS12128"  -> "Relation Error: The AI code ‘MIB01’ in D.E. 2/2 cannot be used on a declaration with controlled goods (Additional Procedure Codes 1CD, 1CG, 2CD or 2CG in D.E. 1/11)",
  "CDS12129"  -> "Relation Error: The Authorisation Type ‘MIB’ in D.E. 3/39 cannot be used for exports across the Northern Ireland border (Authorisation Type ‘NIRE’)",
  "CDS12130"  -> "Relation Error: Conflicting autodeparture prompts. Either ‘MIB01’ or ‘NIRO2’ can be declared in D.E. 2/2 but not both together on the same declaration",
  "CDS12131"  -> "Relation Error: Conflicting autodeparture prompts. Either ‘MIB02’ or ‘NIRO1’ can be declared in D.E. 2/2 but not both together on the same declaration",
  "CDS13000"  -> "Credibility check: incredible value found",
  "CDS19999"  -> "Additional errors found",
  "CDS20001"  -> "Related movement not (yet) found",
  "CDS20003"  -> "Related movement not found",
  "CDS40001"  -> "Missing reference date",
  "CDS40002"  -> "Invalid because of future reference date",
  "CDS40003"  -> "Commodity code can not be declared",
  "CDS40004"  -> "Subheading can not be declared",
  "CDS40005"  -> "Additional antidumping code missing",
  "CDS40006"  -> "Multiple meursing additional codes",
  "CDS40007"  -> "Duplicate value",
  "CDS40008"  -> "Additional agricultural code missing",
  "CDS40010"  -> "Data element value does not apply",
  "CDS40011"  -> "Missing data element value",
  "CDS40012"  -> "Data element has invalid format",
  "CDS40013"  -> "Data element contains invalid value",
  "CDS40040"  -> "Non existing value",
  "CDS40044"  -> "Disallowed Document",
  "CDS40045"  -> "Missing document",
  "CDS40046"  -> "Condition not fulfilled",
  "CDS40047"  -> "Prohibition",
  "CDS40048"  -> "Provisional measure closed",
  "CDS40049"  -> "Quota exhausted",
  "CDS40050"  -> "Quota critical",
  "CDS40051"  -> "Quota blocked",
  "CDS40052"  -> "Quota blocked and critical",
  "CDS40053"  -> "Quota suspended",
  "CDS40054"  -> "Classification changes for definitive measure",
  "CDS40055"  -> "Internal quota system error",
  "CDS40056"  -> "Parent to commodity code not found.",
  "CDS40057"  -> "Abnormally high drawing request",
  "CDS40058"  -> "Incompatible preference code and country code of despatch",
  "CDS40059"  -> "Incomplete measure or commodity code",
  "CDS40062"  -> "Licence Quota - (e.g. Agricultural quota) not managed by TAXUD",
  "CDS40063"  -> "Incomplete preferential document",
  "CDS40064"  -> "Additional codes for export refund available",
  "CDS40065"  -> "No applicable measures found",
  "CDS40066"  -> "Tariff condition not fulfilled",
  "CDS40067"  -> "Confilcting documents",
  "CDS49997"  -> "Other information",
  "CDS49998"  -> "Other warnings",
  "CDS49999"  -> "Other errors",
  "CDS50001"  -> "Invalid UCR Format, DUCR or MUCR",
  "CDS50002"  -> "MUCR can not be declared into as it is shut",
  "CDS50003"  -> "UCR is not at the top of its' consolidation",
  "CDS50004"  -> "Cannot consolidate the MUCR as it is not shut",
  "CDS50005"  -> "Immediate parent MUCR cannot already be within it's same tree/consolidation",
  "CDS50006"  -> "Cannot find the consolidation",
  "CDS50007"  -> "Consolidation already shut",
  "CDS50008"  -> "UCR Type does not match UCR Format ",
  "CDS50009"  -> "Given parent is not a MUCR",
  "CDS50010"  -> "Declaration does not exist",
  "CDS50011"  -> "UCR is already associated to given MUCR",
  "CDS50012"  -> "Prior movement for the UCR is not at the same location as given on the EDL",
  "CDS50013"  -> "No prior EAL can be found for the UCR at the location given on the EDL",
  "CDS50014"  -> "Not all declaration(s) have P2P ",
  "CDS50015"  -> "Declaration is cancelled/terminated/invalidated/handled externally/rejected",
  "CDS50016"  -> "Unknown Declaration ID, DUCR or MUCR ",
  "CDS50017"  -> "Consolidation has reached maximum number of levels/items within a level ",
  "CDS50018"  -> " Goods Departure/Arrival Date/Time is invalid",
  "CDS50019"  -> "Cannot depart the MUCR from UK as MUCR is not Shut ",
  "CDS50020"  -> "Message sent with a future date/time (greater than 25hours in the future)",
  "CDS50021"  -> "UCR is not for a MUCR",
  "CDS50022"  -> "UCR to be disassociated does not exist ",
  "CDS50023"  -> "UCR to be disassociated is not already associated",
  "CDS50024"  -> "Master UCR/UCR field completion does not match the EAC action ",
  "CDS50025"  -> "MUCR is empty ",
  "CDS50026"  -> "IE906 (Exit message failed validation/processing in DMS) was received as a result of an exit message ",
  "CDS50027"  -> "Role/Location-Based Authorisation failed (PDS) ",
  "CDS50028"  -> "Goods Location is invalid ",
  "CDS50029"  -> "MUCR has been departed ",
  "CDS50030"  -> "UCR cannot be associated as it has been Rejected Upon Arrival"

  )
}
